### PR TITLE
AFNI updates - with bugs fixed from animal_warper, transformations

### PR DESCRIPTION
**Pull request by afni-dglen**
Bugs fixed in animal_warper with reverse order of combination of affine and nonlinear transformations. 

All warps among templates were recomputed. Images were verified for all alignments with AFNI GUI visualization and QC images.

Similarly, all warps for individual subjects to the NMTv2_asym template were  recomputed and verified.

Recomputed phase3 single subject mean coordinates to NMT2 asym template space and phase 4 template mean coordinates from each template space to all the others with resulting coordinates in all 6 template space.

### CODE REVIEW

**Review by niksirbi — COMMENTED** [review]
Thanks @afni-dglen! 

I have a few questions on the new data.

1. The "PHASE3_AFNI_transformed" folder appears to contain 11 subjects, while there should be 16. Are some subjects missing (perhaps the loop missed them)?
2. Given than the transformed .fcsv files have the prefix "final" attached to them, I'm assuming these contain the combined effects of linear + nonlinear registrations. Is it possible to also get the linear-only part (we've done this in for the "RheMAP_transformed" results). I don't think it's strictly necessary, as an ANTs-AFNI comparison could be run on the final results, I'm just wondering if it's possible.

**Comment by afni-dglen** [comment]
@niksirbi, thanks very much for spotting the missing files. It turns out those coordinates from phase2 subject means contain NA NA NA for some of their xyz coordinates, and I wasn't expecting that. I changed the reading and writing function in nl_coords_transform.py to treat those like header lines and just reproduce them in the output. I reran all again and produced all 16 subjects phase3 outputs.

I'm not sure the purpose of just the affine part. I do have the technology though. Let me know if you really want those results to be computed.

**Comment by niksirbi** [comment]
> @niksirbi, thanks very much for spotting the missing files. It turns out those coordinates from phase2 subject means contain NA NA NA for some of their xyz coordinates, and I wasn't expecting that. I changed the reading and writing function in nl_coords_transform.py to treat those like header lines and just reproduce them in the output. I reran all again and produced all 16 subjects phase3 outputs.

Strange, I wasn't expecting NA values either, and my results don't have any. I dug deeper into this and realised the following. 
I'm applying the ANTs transforms to the points in the `PHASE2_output_afid_postQC` folder, which do not contain NAs, while you are applying the AFNI transforms to the points in the `PHASE2_output_afid_postQC_for_PHASE3` folder, which contain NAs.

I'll open this discussion on mattermost, I'm not sure what the difference between these two folders is, and why only one of them contains NAs.

**Comment by niksirbi** [comment]
> I'm not sure the purpose of just the affine part. I do have the technology though. Let me know if you really want those results to be computed.

For the ANTs part, we transformed the points either with linear-only part or the full (linear + nonlinear) transform, to show that the addition of the nonlinear warp decreased the error (distance between ground truth and transformed points). This is of course expected and was done more as a sanity check to verify that our distance metrics are meaningful. I don't think that repeating that "sanity check" for AFNI is necessary.

**Comment by mrneont** [comment]
@niksirbi : you might be the first person ever to suggest that AFNI (or at least its developers) doesn't need a sanity check.  Thanks!

**Comment by bmahmou** [comment]
Hi all! Seems like this issue had presented itself before per [thread in our mattermost channel](https://mattermost.brainhack.org/brainhack/pl/1qw3du7cypbpmx1pfe18pkrtsw)

It appears that _Phase2_output_afid_postQC_for_PHASE3_ uses more stringent QC measurements leading to NAN values and we had previously decided to go ahead with _Phase2_output_afid_postQC_ but unfortunately did not change the folder names : ( 
So going forward we should be using _Phase2_output_afid_postQC_ for all Phase2 data using single subjects data

**Comment by niksirbi** [comment]
Thanks for digging this up @bmahmou !!
So to finalise the AFNI results, we'd have to just re-run Daniel's code with `Phase2_output_afid_postQC` as the input folder.
Let's keep this PR open until that happens.

**Pull request merged**
